spring.application.name=spring-AI
logging.pattern.console=${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}
spring.ai.model.chat=ollama
spring.ai.ollama.chat.options.model=llama3.2:1b